local job = assert(arg[1], "usage: lua filed.lua <CCLA|ICLA> <values.lua>")
assert(job == "CCLA" or job == "ICLA", "job must be CCLA or ICLA")
local vals = assert(arg[2], "usage: lua filed.lua <CCLA|ICLA> <values.lua>")

local lib = assert(loadfile("lib.lua"))()
local env = lib.load_env(".env")
local secret = assert(env.FILING_SECRET, "FILING_SECRET missing in .env")
assert(env.LUATEX and env.LUA, "LUATEX/LUA missing in .env")

local v = assert(loadfile(vals))()

local SIGNATURE = {
  CCLA = {
    "entity_name",
    "rep_title",
    "contact_email",
    "date",
    "signature",
    "sched_extra",
  },
  ICLA = { "name", "email", "platform", "keyfp", "date", "signature" },
}

local SCHEDULE = { "name", "email", "ids", "from" }

local FIELDS = { "verghash", "email", "platformid", "sigdate" }
for _, stem in ipairs(SIGNATURE[job]) do
  FIELDS[#FIELDS + 1] = job .. "_" .. stem
end
if job == "CCLA" then
  for i = 1, 3 do
    for _, s in ipairs(SCHEDULE) do
      FIELDS[#FIELDS + 1] = ("%s_sched%d_%s"):format(job, i, s)
    end
  end
end

local OK = {}
for b = 32, 126 do
  local c = string.char(b)
  if not c:find("[\\%%&#^_~${}]") then
    OK[c] = true
  end
end

local function check(field, s)
  assert(type(s) == "string", field .. " must be a string")
  for i = 1, #s do
    assert(
      OK[s:sub(i, i)],
      field
        .. ": character not permitted at byte "
        .. i
        .. " (printable US-ASCII minus reserved; single line)"
    )
  end
end

for _, f in ipairs(FIELDS) do
  v[f] = v[f] or ""
  check(f, v[f])
end

local a, b =
  lib.read_all(job .. ".vh"):match("\\def\\versionhashA{(%x+)}%s*\\def\\versionhashB{(%x+)}")
assert(a and b, "cannot parse " .. job .. ".vh")
assert(v.verghash == a .. b, "verghash does not match " .. job .. ".vh (wrong instrument version)")

local digest = lib.sha256_hex(v.verghash .. v.email .. v.platformid .. v.sigdate)
local checkcode = lib.check_code(secret, digest)

local tmp = "filed.tex"
do
  local f = assert(io.open(tmp, "w"))
  f:write("% generated by filed.lua; deleted after the run\n")
  for _, k in ipairs(FIELDS) do
    f:write("\\docfield{" .. k .. "}{" .. v[k] .. "}\n")
  end
  f:write("\\sethmacsecret{" .. secret .. "}\n")
  f:close()
  lib.run("chmod 600 " .. tmp)
end

local out = job .. "-filed.pdf"
local ok, err = pcall(
  lib.run,
  string.format(
    "%s --fmt=minim --interaction=nonstopmode --jobname=%s-filed "
      .. "'\\def\\CLAFILED{}\\input %s.tex' > %s-filed.stdout 2>&1",
    env.LUATEX,
    job,
    job,
    job
  )
)
os.remove(tmp)
assert(ok, err)

lib.run(env.LUA .. " normalize.lua " .. out)

local raw = lib.read_all(out)
assert(not raw:find("/AcroForm", 1, true), "live AcroForm remains in " .. out)

local p = assert(io.popen("pdftotext " .. out .. " - | tr -d ' \\n'", "r"))
local text = p:read("a")
p:close()
assert(not text:find("VVVVVVVV", 1, true), "unstamped placeholder in " .. out)
assert(text:find(digest, 1, true), "footer digest missing from " .. out)
assert(text:find("CHECK:" .. checkcode, 1, true), "footer check code missing from " .. out)

if env.QPDF and env.QPDF ~= "" then
  lib.run(env.QPDF .. " --check " .. out)
end

print("digest:     " .. digest)
print("check code: " .. checkcode)
print("filed copy: " .. out)
