local path = assert(arg[1], "usage: lua normalize.lua <file.pdf>")
local f = assert(io.open(path, "rb"))
local data = f:read("a")
f:close()
local zero = string.rep("0", 32)
local norm, n = data:gsub("/ID %[ <%x+> <%x+> %]", "/ID [ <" .. zero .. "> <" .. zero .. "> ]", 1)
assert(n == 1, "trailer ID not found exactly once in " .. path)
local o = assert(io.open(path, "wb"))
o:write(norm)
o:close()
